///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OneDataModelData {
/*
{
  "picUrl": "ZZZZZZZ",
  "title": "YYYYYYYYYY",
  "year": "2017",
  "month": 5,
  "day": 9,
  "details": "XXXXXXXX"
}
*/

  String? picUrl;
  String? title;
  String? year;
  int? month;
  int? day;
  String? details;

  OneDataModelData({
    this.picUrl,
    this.title,
    this.year,
    this.month,
    this.day,
    this.details,
  });
  OneDataModelData.fromJson(Map<String, dynamic> json) {
    picUrl = json['picUrl']?.toString();
    title = json['title']?.toString();
    year = json['year']?.toString();
    month = json['month']?.toInt();
    day = json['day']?.toInt();
    details = json['details']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['picUrl'] = picUrl;
    data['title'] = title;
    data['year'] = year;
    data['month'] = month;
    data['day'] = day;
    data['details'] = details;
    return data;
  }
}

class OneDataModel {
/*
{
  "code": 1,
  "msg": "数据返回成功！",
  "data": [
    {
      "picUrl": "ZZZZZZZ",
      "title": "YYYYYYYYYY",
      "year": "2017",
      "month": 5,
      "day": 9,
      "details": "XXXXXXXX"
    }
  ]
}
*/

  int? code;
  String? msg;
  List<OneDataModelData?>? data;

  OneDataModel({
    this.code,
    this.msg,
    this.data,
  });
  OneDataModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    msg = json['msg']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <OneDataModelData>[];
      v.forEach((v) {
        arr0.add(OneDataModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['msg'] = msg;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
