///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OneDataModelData {
/*
{
  "picUrl": "http://www.todayonhistory.com/uploadfile/2017/0511/20170511090235762.jpg",
  "title": "原国务委员、国务院原副总理钱其琛病逝 享年90岁",
  "year": "2017",
  "month": 5,
  "day": 9
}
*/

  String? picUrl;
  String? title;
  String? year;
  int? month;
  int? day;

  OneDataModelData({
    this.picUrl,
    this.title,
    this.year,
    this.month,
    this.day,
  });
  OneDataModelData.fromJson(Map<String, dynamic> json) {
    picUrl = json['picUrl']?.toString();
    title = json['title']?.toString();
    year = json['year']?.toString();
    month = json['month']?.toInt();
    day = json['day']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['picUrl'] = picUrl;
    data['title'] = title;
    data['year'] = year;
    data['month'] = month;
    data['day'] = day;
    return data;
  }
}

class OneDataModel {
/*
{
  "code": 1,
  "msg": "数据返回成功！",
  "data": [
    {
      "picUrl": "http://www.todayonhistory.com/uploadfile/2017/0511/20170511090235762.jpg",
      "title": "原国务委员、国务院原副总理钱其琛病逝 享年90岁",
      "year": "2017",
      "month": 5,
      "day": 9
    }
  ]
}
*/

  int? code;
  String? msg;
  List<OneDataModelData?>? data;

  OneDataModel({
    this.code,
    this.msg,
    this.data,
  });
  OneDataModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    msg = json['msg']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <OneDataModelData>[];
      v.forEach((v) {
        arr0.add(OneDataModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['msg'] = msg;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
